vim.g.mapleader = " "

vim.keymap.set("n", "<leader>ps", function()
    require('telescope.builtin').grep_string({ search = vim.fn.input("Grep for > ") })
end)
vim.keymap.set("n", "<leader>vd", "<esc>:call CocActionAsync('jumpDefinition')<CR>")
vim.keymap.set("n", "<leader>gp", "<esc>:!git pull<CR>")
vim.keymap.set("n", "<leader>gs", "<esc>:Git<CR>")
vim.keymap.set("n", "<leader>gd", "<esc>:Git diff<CR>")
vim.keymap.set("n", "<leader>ga", "<esc>:Git add %<CR>")
vim.keymap.set("n", "<leader>gc", "<esc>:Git commit<CR>")
vim.keymap.set("n", "<leader>ft", ":NERDTreeToggle<CR>")
vim.keymap.set("n", "<leader>ff", ":NERDTreeFocus<CR>")

vim.keymap.set("n", "j", "gj")
vim.keymap.set("n", "k", "gk")
vim.keymap.set("n", "B", "^")
vim.keymap.set("n", "E", "$")
vim.keymap.set("n", "$", "<nop>")
vim.keymap.set("n", "^", "<nop>")
vim.keymap.set("v", "B", "^")
vim.keymap.set("v", "E", "$")
vim.keymap.set("v", "$", "<nop>")
vim.keymap.set("v", "^", "<nop>")
vim.keymap.set("i", "jk", "<esc>")
vim.keymap.set("n", "<leader>ww", "<esc>:w!<cr>")
vim.keymap.set("n", "<leader>wq", "<esc>:wq!<cr>")
vim.keymap.set("n", "<leader>qq", "<esc>:q!<cr>")
vim.keymap.set("n", "<c-F>", "<esc>:Files<cr>")
vim.keymap.set("n", "<c-T>", "<esc>:tabnew<cr>:Files<cr>")
vim.keymap.set("n", "<c-R>", "<esc>:tabn<cr>")
vim.keymap.set("n", "<c-Z>", ":UndotreeToggle<CR>")

vim.api.nvim_exec('inoremap <expr> <Tab>   pumvisible() ? "\\<C-n>" : "\\<Tab>"', false)
vim.api.nvim_exec('inoremap <expr> <S-Tab> pumvisible() ? "\\<C-p>" : "\\<S-Tab>"', false)

